# Given a list of numbers, create a NumPy array and find
# the sum and product of its elements

In [1]:
import numpy as np

num = [1,2,3,4,5,6,7,8,9]
ar = np.array(num)

#sum
print("sum = " ,np.sum(ar))
print("products = " , np.prod(ar))

sum =  45
products =  362880


# Implement a program that generates a NumPy array with
# numbers from 0 to 9 and reshapes it into a 3x3 matrix

In [2]:
import numpy as np

arr = np.array([0,1,2,3,4,5,6,7,8])

In [3]:
arr = arr.reshape(3,3)

In [4]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# Write a Python program that uses NumPy to find the
# mean, median, and standard deviation of a dataset

In [5]:
import numpy as np 

numbs = [1,2,3,4,5,6,7,8,9]
numbers = np.array(numbs)

mean = np.mean(numbers)

meadian = np.median(numbers)

standard_deviation = np.std(numbers)

In [6]:
print(f"mean = {mean}, median = {meadian} , std = {standard_deviation} ")

mean = 5.0, median = 5.0 , std = 2.581988897471611 


# Create a function that takes a list of numbers and returns
# the NumPy array sorted in ascending order

In [7]:
import numpy as np

def sortArray(l):
    li = np.array(l)
    return np.sort(li)
    
print(sortArray([1,3,2,5,4]))

[1 2 3 4 5]


# Given a list of lists, create a 2D NumPy array and find the
# sum of elements in each row and column

In [8]:
ar1 = np.array([[1,2,3] , [4,5,6], [7,1,2]])

In [9]:
ar1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 2]])

In [10]:
# sum about columns
ar1.sum(axis=0)

array([12,  8, 11])

In [11]:
# sum about rows
ar1.sum(axis=1)

array([ 6, 15, 10])

# Implement a program that generates a random NumPy
# array and finds the maximum and minimum values

In [12]:
r = np.random.rand(5)

In [13]:
# random 1D sarray
r

array([0.99281105, 0.28312148, 0.08998809, 0.19883025, 0.07446494])

In [14]:
# max in array
np.max(r)

0.9928110533832841

In [15]:
# min in array
np.min(r)

0.07446493835550494

# Write a function that takes a NumPy array and returns a
# new array with all elements squared

In [16]:
nr = np.array([1,2,3,4])

def sqr(l):
    return np.square(l)
    
print(sqr(nr))

[ 1  4  9 16]


# Given a NumPy array, calculate the dot product of the
# array with itself

In [17]:
np1 = np.array([1,2])
product = np.dot(np1,np1)

In [18]:
product

5

# Create a program that uses NumPy to calculate the
# inverse of a 2x2 matrix

In [19]:
mat = np.array([[1,2] , [3,4]])

In [20]:
mat

array([[1, 2],
       [3, 4]])

In [21]:
if np.linalg.det(mat) == 0:
    print("Not invertible")
else:
    inverse = np.linalg.inv(mat)
    print( inverse)

[[-2.   1. ]
 [ 1.5 -0.5]]


# Implement a function that takes a NumPy array and
# returns the transpose of the array.

In [22]:
def transp(l):
    return l.T
print(transp(mat))

[[1 3]
 [2 4]]
